name: deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - run: pip install mkdocs-material mkdocs-redirects

    - name: Mkdocs build zh-CN
      run: mkdocs build -f mkdocs.zh-CN.yml
    - name: Deploy zh-CN
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        destination_dir: zh-CN

    - name: Mkdocs build en-US
      run: mkdocs build -f mkdocs.en-US.yml
    - name: Deploy en-US
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
        destination_dir: en-US
